DROP TABLE IF EXISTS POKEMON;

CREATE TABLE POKEMON (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  POKEDEX_NUMBER int NOT NULL,
  NAME  VARCHAR(250) NOT NULL,
  TYPE_1 VARCHAR(250) NOT NULL,
  TYPE_2 VARCHAR(250) DEFAULT NULL,
  MAX_PC NUMBER NOT NULL,
  ATK NUMBER NOT NULL,
  DEF NUMBER NOT NULL,
  STA NUMBER NOT NULL,
  REGION VARCHAR(250) NOT NULL
);